console.log(document);
console.log(typeof document);
console.log(window);
console.log(typeof window);
const h1=document.querySelector("h1");
console.log(h1); 
const liurl=document.getElementById("URL");
liurl.innerText=window.document.URL;
console.log(window.localStorage);
localStorage.setItem('Hello','Hi this is js course');
console.log(window.cookie);
console.log(window.close);
console.log(window.console);
console.log(window.confirm);
console.log(window.alert);
console.log(window.prompt);
console.log(window.CSS);
console.log(window.setTimeout);
console.log(window.sessionStorage);